In [70]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\asus\anaconda3\lib\site-packages (4.11.2)
Requirement already satisfied: trio~=0.17 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sortedcontainers in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.2)
Requirement already satisfied: attrs>=20.1.0 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: outcome in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sniffio in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\asus\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\asus\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\asus\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [27]:
!pip install --upgrade selenium

Requirement already satisfied: selenium in c:\users\asus\anaconda3\lib\site-packages (4.11.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: trio~=0.17 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.22.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.2)
Requirement already satisfied: sniffio in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sortedcontainers in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\asus\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\asus\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\asus\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = 
https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: 
A) Rank 
B) Name 
C) Artist 
D) Upload date 
E) Views

In [71]:
import selenium

import pandas as pd

import time

from bs4 import BeautifulSoup

from selenium import webdriver

from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException

import requests

from selenium.webdriver.common.by import By

In [29]:
driver = webdriver.Chrome()
#driver.maximize_window()
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [84]:
rank = []
video_names = []
video_uploader_name = []
views = []
upload_dates = []

try:
    rank_obj = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')[:30]
    for i in rank_obj:
        rank.append(i.text)
except NoSuchElementException :
    rank.append('-')
    
try:
    videoname_obj = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')[:30]
    for i in videoname_obj:
        video_names.append(i.text.split('[')[0][1:-1])
except NoSuchElementException :
    video_names.append('-')
    
try:
    uploader_obj = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')[:30]
    for i in uploader_obj:
        video_uploader_name.append(i.text)
except NoSuchElementException :
    video_uploader_name.append('-')
    
try:
    view_obj = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')[:30]
    for i in view_obj:
        views.append(i.text)
except NoSuchElementException :
    views.append('-')
    
try:
    date_obj = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')[:30]
    for i in date_obj:
        upload_dates.append(i.text)
except NoSuchElementException :
    upload_dates.append('-')

In [87]:
df=pd.DataFrame({'rank':rank, 'video_name':video_names,'uploader':video_uploader_name,'Views in Billions':views,'upload_date':upload_dates})
df

,rank,video_name,uploader,Views in Billions,upload_date
0,1.,Baby Shark Dance,Pinkfong Baby Shark - children's songs,13.18,"June 17, 2016"
1,2.,Despacito,Luis Fonsi,8.23,"January 12, 2017"
2,3.,Johny Johny Yes Papa,LooLoo Kids - nursery rhymes,6.76,"October 8, 2016"
3,4.,Bath Song,Cocomelon - nursery rhymes,6.33,"May 2, 2018"
4,5.,Shape of You,Ed Sheeran,6.05,"January 30, 2017"
5,6.,See You Again,Wiz Khalifa,5.98,"April 6, 2015"
6,7.,Wheels on the Bus,Cocomelon - nursery rhymes,5.46,"May 24, 2018"
7,8.,Phonics Song with Two Words,ChuChu TV - children's songs,5.42,"March 6, 2014"
8,9.,Uptown Funk,Mark Ronson,5.00,"November 19, 2014"
9,10.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV - children's songs,4.94,"February 27, 2018"
10,11.,Gangnam Style,Psy,4.86,"July 15, 2012"
11,12.,Masha and the Bear – Recipe for Disaster,Get Movies - children's songs,4.55,"January 31, 2012"
12,13.,Dame Tu Cosita,El Chombo,4.41,"April 5, 2018"
13,14.,Axel F,Crazy Frog,4.00,"June 16, 2009"
14,15.,Sugar,Maroon 5,3.91,"January 14, 2015"
15,16.,Roar,Katy Perry,3.84,"September 5, 2013"
16,17.,Counting Stars,OneRepublic,3.84,"May 31, 2013"
17,18.,Baa Baa Black Sheep,Cocomelon - nursery rhymes,3.73,"June 25, 2018"
18,19.,Sorry,Justin Bieber,3.69,"October 22, 2015"
19,20.,Waka Waka (This Time for Africa),Shakira,3.68,"June 4, 2010"
20,21.,Thinking Out Loud,Ed Sheeran,3.63,"October 7, 2014"
21,22.,Lakdi Ki Kathi,Jingle Toons,3.63,"June 14, 2018"
22,23.,Dark Horse,Katy Perry,3.56,"February 20, 2014"
23,24.,Perfect,Ed Sheeran,3.51,"November 9, 2017"
24,25.,Faded,Alan Walker,3.49,"December 3, 2015"
25,26.,Let Her Go,Passenger,3.48,"July 25, 2012"
26,27.,Humpty the train on a fruits ride,Kiddiestv Hindi - children's songs,3.51,"January 26, 2018"
27,28.,Girls Like You,Maroon 5,3.45,"May 31, 2018"
28,29.,Bailando,Enrique Iglesias,3.43,"April 11, 2014"
29,30.,Lean On,Major Lazer,3.43,"March 22, 2015"

# 2. Scrape the details team India’s international fixtures from bcci.tv. 
Url = https://www.bcci.tv/.
You need to find following details: 
A) Match title (I.e. 1 ODI) 
B) Series 
C) Place 
D) Date 
E) Time 
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [30]:
driver = webdriver.Chrome()
driver.get("https://www.bcci.tv/")

In [31]:
fixture_click = driver.find_element(By.XPATH,'(//a[@class="moreMatchesLink"])[1]')
fixture_click.click()

In [98]:
Name=[]
Series=[]
Place=[]
Date=[]
Time=[]

try:
    name_tag = driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in name_tag:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-') 
    
try:
    series_tag = driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
    for i in series_tag:
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')
    
try:
    place_tag = driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
    for i in place_tag:
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')
    
try:
    date_tag = driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
    for i in date_tag:
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')

try:
    time_tag = driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
    for i in time_tag:
        Time.append(i.text)
except NoSuchElementException:
    Time.append('-')

In [99]:
print(len(Name),len(Series),len(Place),len(Date),len(Time))

8 8 8 8 8

In [100]:
df=pd.DataFrame({'Match title':Name,' Series': Series,'Place':Place,'Date':Date,'Time':Time})
df

,Match title,Series,Place,Date,Time
0,1st T20I -,INDIA TOUR OF IRELAND 2023,"The Village,",18 AUG 2023,7:30 PM IST
1,2nd T20I -,INDIA TOUR OF IRELAND 2023,"The Village,",20 AUG 2023,7:30 PM IST
2,3rd T20I -,INDIA TOUR OF IRELAND 2023,"The Village,",23 AUG 2023,7:30 PM IST
3,1st ODI -,ASIA CUP 2023,"Pallekele International Cricket Stadium,",2 SEP 2023,10:00 AM IST
4,2nd ODI -,ASIA CUP 2023,"Pallekele International Cricket Stadium,",4 SEP 2023,10:00 AM IST
5,1st ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Punjab Cricket Association IS Bindra Stadium,",22 SEP 2023,1:30 PM IST
6,2nd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Holkar Cricket Stadium,",24 SEP 2023,1:30 PM IST
7,3rd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Saurashtra Cricket Association Stadium,",27 SEP 2023,1:30 PM IST

# 3. Scrape the details of State-wise GDP of India from statisticstime.com. 
Url = http://statisticstimes.com/
You have to find following details: A)
Rank 
B) State 
C) GSDP(18-19)- at current prices 
D) GSDP(19-20)- at current prices 
E) Share(18-19) 
F) GDP($ billion) 
Note: - From statisticstimes home page you have to reach to economy page through code.

In [101]:
driver = webdriver.Chrome()
driver.get("http://statisticstimes.com/")

In [104]:
economy = driver.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/button').click()

In [108]:
economy = driver.find_element(By.XPATH,'//div[@class="dropdown-content"]/a[3]')
india_link = economy.get_attribute('href')
driver.get(india_link)

In [120]:
india_state = driver.find_element(By.XPATH,'//ul[@style="list-style-type:none;margin-left:20px;"]/li/a')
click_url = india_state.get_attribute('href')
driver.get(click_url)
time.sleep(5)

In [179]:
Rank = []
State = []
Gsdp_19_20 = []
Gsdp_18_19 = []
Share_18_19 = []
Gdp_billion = []

In [180]:
rank_tag = driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
for i in rank_tag:
    Rank.append(i.text)
    
state_tag = driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
for i in state_tag:
    State.append(i.text)
    
gsdp_19_20_tag = driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
for i in gsdp_19_20_tag:
    Gsdp_19_20.append(i.text)

gsdp_18_19_tag = driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
for i in gsdp_18_19_tag:
    Gsdp_18_19.append(i.text)
    
share_tag = driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
for i in share_tag:
    Share_18_19.append(i.text)
    
gdp_billion_tag = driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
for i in gdp_billion_tag:
    Gdp_billion.append(i.text)

In [182]:
print(len(Rank),len(State),len(Gsdp_18_19),len(Gsdp_19_20),len(Share_18_19),len(Gdp_billion))

33 33 33 33 33 33

In [186]:
df=pd.DataFrame({'Rank':Rank,'State':State,'GSDP(18-19)- at current prices':Gsdp_18_19,'GSDP(19-20)- at current prices':Gsdp_19_20,'Share(18-19)':Share_18_19,'GDP($ billion)':Gdp_billion})
df

,Rank,State,GSDP(18-19)- at current prices,GSDP(19-20)- at current prices,Share(18-19),GDP($ billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 4. Scrape the details of trending repositories on Github.com. 
Url = https://github.com/
You have to find the following details: 
A) Repository title 
B) Repository description 
C) Contributors count 
D) Language used

In [273]:
driver = webdriver.Chrome()
driver.get('https://github.com/')

In [274]:
click_opensource = driver.find_element(By.XPATH,'//ul[@class="d-lg-flex list-style-none"]/li[3]/button')
click_opensource.click()

In [275]:
trending = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

repository_title = []
repository_description = []
contributors = []

In [295]:
contributors = []

contributors_tag = driver.find_elements(By.XPATH,'//span[@class="d-inline-block mr-3"]')
for i in contributors_tag:
    contributors.append(i.text)

In [293]:
repository_tag = driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]')
for i in repository_tag:
    repository_title.append(i.text)
    
description_tag = driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in description_tag:
    repository_description.append(i.text)
    
contributors_tag = driver.find_elements(By.XPATH,'//span[@class="d-inline-block mr-3"]')
for i in contributors_tag:
    contributors.append(i.text)

NameError: name 'contributors' is not defined

# 5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details: 
A) Song name 
B) Artist name 
C) Last week rank 
D) Peak rank 
E) Weeks on board 
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [237]:
driver = webdriver.Chrome()
driver.get('https:/www.billboard.com/')

In [238]:
charte = driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
charte.click()

In [239]:
hot_100 = driver.find_element(By.XPATH,'//a[@class="c-label__link lrv-u-color-brand-primary u-color-black@mobile-max a-font-primary-bold lrv-u-font-size-32 u-whitespace-nowrap@tablet"]')
hot_100.click()

In [241]:
song_name = []
artist_name = []
last_week_rank = []
peak_rank = []
weeks_on_board = []

In [242]:
song_tag = driver.find_elements(By.ID,"title-of-a-story")
for i in song_tag:
    song_name.append(i.text)
song_names = song_name[6::4][:100]

artist_tag = driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet"]')
for i in artist_tag:
    artist_name.append(i.text)
    
artist_tags = driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
for i in artist_tags:
    artist_name.append(i.text)
    
week_rank_tag = driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
for i in week_rank_tag:
    last_week_rank.append(i.text)
last_week_ranks=last_week_rank[0::2]

peak_rank_tag = driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"]')
for i in peak_rank_tag:
    peak_rank.append(i.text)
peak_ranks=peak_rank[1::2]

week_on_board_tag = driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
for i in week_on_board_tag:
    weeks_on_board.append(i.text)
    weeks_on_boards = weeks_on_board[1::2]

In [246]:
# this is second method it showing me all the answer in one class
all_details = []
all_detail = driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in all_detail:
    all_details.append(i.text)
    
all_details

['1\nLast Night\nMorgan Wallen\n1\n1\n28',
 '2\nFast Car\nLuke Combs\n2\n2\n20',
 '3\nCruel Summer\nTaylor Swift\n4\n3\n14',
 '4\nCalm Down\nRema & Selena Gomez\n6\n3\n49',
 '5\nFukumean\nGunna\n7\n4\n8',
 '6\nVampire\nOlivia Rodrigo\n9\n1\n6',
 '7\nDance The Night\nDua Lipa\n10\n7\n11',
 '8\nBarbie World\nNicki Minaj & Ice Spice With Aqua\n8\n7\n7',
 '9\nFlowers\nMiley Cyrus\n12\n1\n30',
 '10\nSnooze\nSZA\n15\n10\n35',
 '11\nAll My Life\nLil Durk Featuring J. Cole\n13\n2\n13',
 '12\nMeltdown\nTravis Scott Featuring Drake\n3\n3\n2',
 '13\nKarma\nTaylor Swift Featuring Ice Spice\n20\n2\n22',
 '14\nWhat Was I Made For?\nBillie Eilish\n22\n14\n4',
 '15\nNEW\nPaint The Town Red\nDoja Cat\n-\n15\n1',
 '16\nNeed A Favor\nJelly Roll\n24\n14\n19',
 '17\nReligiously\nBailey Zimmerman\n33\n17\n14',
 '18\nAnti-Hero\nTaylor Swift\n31\n1\n42',
 '19\nKill Bill\nSZA\n29\n1\n35',
 "20\nCreepin'\nMetro Boomin, The Weeknd & 21 Savage\n32\n3\n36",
 '21\nTry That In A Small Town\nJason Aldean\n21\n1\n4',
 '22\nI Know ?\nTravis Scott\n11\n11\n2',
 "23\nThinkin' Bout Me\nMorgan Wallen\n37\n9\n23",
 '24\nFE!N\nTravis Scott Featuring Playboi Carti\n5\n5\n2',
 '25\nCupid\nFifty Fifty\n41\n17\n21',
 '26\nFavorite Song\nToosii\n39\n5\n25',
 '27\nK-POP\nTravis Scott, Bad Bunny & The Weeknd\n18\n7\n3',
 '28\nSeven\nJung Kook Featuring Latto\n30\n1\n4',
 '29\nTelekinesis\nTravis Scott Featuring SZA & Future\n26\n26\n2',
 '30\nDial Drunk\nNoah Kahan With Post Malone\n44\n25\n8',
 '31\nElla Baila Sola\nEslabon Armado X Peso Pluma\n42\n4\n21',
 '32\nNext Thing You Know\nJordan Davis\n45\n23\n29',
 '33\nLove You Anyway\nLuke Combs\n48\n15\n26',
 '34\nThought You Should Know\nMorgan Wallen\n50\n7\n52',
 '35\nChemical\nPost Malone\n35\n13\n17',
 '36\nBury Me In Georgia\nKane Brown\n51\n36\n13',
 '37\nYou, Me, & Whiskey\nJustin Moore & Priscilla Block\n47\n37\n14',
 '38\nLa Bebe\nYng Lvcas x Peso Pluma\n52\n11\n21',
 '39\nWatermelon Moonshine\nLainey Wilson\n71\n39\n7',
 '40\nSearch & Rescue\nDrake\n54\n2\n18',
 '41\nPut It On Da Floor Again\nLatto Featuring Cardi B\n57\n13\n10',
 '42\nUn x100to\nGrupo Frontera X Bad Bunny\n59\n5\n17',
 '43\nLaLa\nMyke Towers\n60\n43\n5',
 '44\nMy Eyes\nTravis Scott\n19\n19\n2',
 '45\nDaylight\nDavid Kushner\n74\n45\n17',
 '46\nTopia Twins\nTravis Scott Featuring Rob49 & 21 Savage\n17\n17\n2',
 '47\nLady Gaga\nPeso Pluma, Gabito Ballesteros & Junior H\n63\n35\n7',
 "48\nBaby Don't Hurt Me\nDavid Guetta, Anne-Marie & Coi Leray\n64\n48\n12",
 '49\nRE- ENTRY\nBlank Space\nTaylor Swift\n-\n1\n37',
 '50\nWhat It Is (Block Boy)\nDoechii Featuring Kodak Black\n66\n50\n14',
 '51\nDeli\nIce Spice\n58\n41\n3',
 '52\nWhere She Goes\nBad Bunny\n61\n8\n12',
 '53\nPrincess Diana\nIce Spice & Nicki Minaj\n62\n4\n17',
 '54\nPeaches & Eggplants\nYoung Nudy Featuring 21 Savage\n69\n52\n10',
 '55\nIn Your Love\nTyler Childers\n43\n43\n2',
 '56\nMourning\nPost Malone\n40\n36\n12',
 '57\nArea Codes\nKaliii\n65\n33\n14',
 '58\nYour Heart Or Mine\nJon Pardi\n72\n53\n13',
 '59\nWhite Horse\nChris Stapleton\n79\n31\n3',
 '60\nSabor Fresa\nFuerza Regida\n70\n26\n7',
 '61\nTruck Bed\nHARDY\n91\n61\n8',
 '62\nEyes Closed\nEd Sheeran\n73\n19\n20',
 "63\nI Can See You (Taylor's Version) (From The Vault)\nTaylor Swift\n76\n5\n5",
 '64\nThank God\nTravis Scott\n16\n16\n2',
 '65\nTulum\nPeso Pluma & Grupo Frontera\n75\n43\n6',
 '66\nSuper Shy\nNewJeans\n77\n48\n5',
 '67\nPopular\nThe Weeknd, Playboi Carti & Madonna\n86\n43\n10',
 '68\nNEW\nGood Good\nUsher, Summer Walker & 21 Savage\n-\n68\n1',
 '69\nEverything I Love\nMorgan Wallen\n83\n14\n24',
 '70\nHyaena\nTravis Scott\n14\n14\n2',
 '71\nModern Jam\nTravis Scott Featuring Teezo Touchdown\n23\n23\n2',
 '72\nShake Sumn\nDaBaby\n84\n65\n12',
 '73\nJaded\nMiley Cyrus\n93\n56\n12',
 '74\nStand By Me\nLil Durk Featuring Morgan Wallen\n81\n22\n11',
 '75\nSpeed Drive\nCharli XCX\n78\n73\n3',
 '76\nFragil\nYahritza y Su Esencia x Grupo Frontera\n82\n69\n16',
 '77\nTQM\nFuerza Regida\n85\n34\n12',
 "78\nRE- ENTRY\nAngels Don't Always Have Wings\nThomas Rhett\n-\n78\n3",
 '79\nJohnny Dang\nThat Mexican OT, Paul Wall & DRODi\n100\n79\n4',
 '80\nMemory Lane\nOld Dominion\n95\n27\n19',
 '81\nHeartbroken\nDiplo, Jessie Murph & Polo G\n94\n64\n3',
 '82\nNEW\nEl Amor de Su Vida\nGrupo Frontera & Grupo Firme\n-\n82\n1',
 '83\nJealousy\nOffset & Cardi B\n55\n55\n2',
 '84\nOh U Went\nYoung Thug Featuring Drake\n96\n19\n7',
 '85\nTil Further Notice\nTravis Scott Featuring James Blake & 21 Savage\n38\n38\n2',
 '86\nRE- ENTRY\nOklahoma Smoke Show\nZach Bryan\n-\n86\n3',
 '87\nSirens\nTravis Scott\n27\n27\n2',
 '88\nRE- ENTRY\nSave Me\nJelly Roll With Lainey Wilson\n-\n85\n8',
 "89\nGod's Country\nTravis Scott\n28\n28\n2",
 "90\nI'm Just Ken\nRyan Gosling\n92\n87\n3",
 '91\nICU\nCoco Jones\n97\n62\n19',
 '92\nSkitzo\nTravis Scott Featuring Young Thug\n34\n34\n2',
 '93\nDelresto (Echoes)\nTravis Scott & Beyonce\n25\n25\n2',
 '94\nRE- ENTRY\nSee You Again\nTyler, The Creator Featuring Kali Uchis\n-\n44\n16',
 '95\nPound Town 2\nSexyy Red & Tay Keith & Nicki Minaj\n98\n66\n10',
 '96\nRE- ENTRY\nLagunas\nPeso Pluma & Jasiel Nunez\n-\n77\n6',
 '97\nOverdrive\nPost Malone\n68\n47\n3',
 '98\nBzrp Music Sessions, Vol. 55\nBizarrap & Peso Pluma\n99\n31\n10',
 '99\nRE- ENTRY\nDawns\nZach Bryan Featuring Maggie Rogers\n-\n42\n15',
 '100\nRE- ENTRY\nRubicon\nPeso Pluma\n-\n63\n6']

In [243]:
print(len(song_names),len(artist_name),len(last_week_ranks),len(peak_ranks),len(weeks_on_boards))

100 100 100 100 100

In [245]:
df=pd.DataFrame({'Song name':song_names,'Artist name':artist_name,'Last week rank':last_week_ranks,'Peak rank':peak_ranks,'Weeks on board':weeks_on_boards})
df

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,Last Night,Morgan Wallen,1,1,28
1,Fast Car,Luke Combs,2,2,20
2,Cruel Summer,Taylor Swift,4,3,14
3,Calm Down,Rema & Selena Gomez,6,3,49
4,Fukumean,Gunna,7,4,8
...,...,...,...,...,...
95,Lagunas,Peso Pluma & Jasiel Nunez,-,77,6
96,Overdrive,Post Malone,68,47,3
97,"Bzrp Music Sessions, Vol. 55",Bizarrap & Peso Pluma,99,31,10
98,Dawns,Zach Bryan Featuring Maggie Rogers,-,42,15
99,Rubicon,Peso Pluma,-,63,6

In [ ]:
all_details = []
all_detail = driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in all_detail:
    all_details.append(i.text)
    
all_details